// Each row contains matching English and Tagalog instructions for one tab step.
const TAB_TUTORIALS = {
 home: [
  {en:['Home: find your way around','Use the navigation to open Budget, Meal Planner, Prices, Palengke AI, or Grocery.','On desktop, use the sidebar. On mobile, use the tab strip; scroll it sideways to find more tabs.','The Tutorial button is in the sidebar or mobile menu. Each tab also has its own guide.'],tl:['Home: alamin ang mga bahagi','Gamitin ang menu para buksan ang Budget, Meal Planner, Prices, Palengke AI, o Grocery.','Sa desktop, gamitin ang sidebar. Sa mobile, i-scroll nang pahalang ang hanay ng mga tab para makita ang iba.','Nasa sidebar o mobile menu ang Tutorial. May sariling gabay din ang bawat tab.']},
  {en:['Read the Home overview','Home brings together price movements, saving tips, fuel references, and a meal idea.','Price movements are a quick summary. Open Prices to inspect the source date, region, and selling unit.','Fuel figures and meal suggestions are references, not a promise of your actual spending.'],tl:['Basahin ang buod sa Home','Makikita rito ang galaw ng presyo, tip sa pagtitipid, sanggunian sa gasolina, at mungkahing pagkain.','Buod lamang ang galaw ng presyo. Buksan ang Prices para makita ang petsa, rehiyon, at yunit.','Gabay lamang ang presyo ng gasolina at mungkahing pagkain; maaaring iba ang aktuwal mong gastos.']},
  {en:['Choose your next task','Start where you need help today.','Use Budget to record income and expenses, or Meal Planner to plan meals for your household.','Use Grocery to build a shopping list, then set its own shopping budget.'],tl:['Piliin ang susunod mong gagawin','Magsimula sa bahaging kailangan mo ngayon.','Gamitin ang Budget para sa kita at gastusin, o Meal Planner para sa pagkain ng pamilya.','Gamitin ang Grocery para sa listahan ng bibilhin at hiwalay nitong badyet.']}
 ],
 budget: [
  {en:['Budget: create a month folder','Start with + Add New Budget.','Choose the statement month and select Create Month Folder.','Open a saved month folder to work with its income and expenses.'],tl:['Budget: gumawa ng folder ng buwan','Magsimula sa + Add New Budget.','Piliin ang buwan at pindutin ang Create Month Folder.','Buksan ang naka-save na folder para sa kita at gastusin ng buwang iyon.']},
  {en:['Record your income','Use + Add in the income section.','Enter the requested description, amount, and schedule details.','Select Save Allocation to record it, or Cancel to close the form without saving.'],tl:['Itala ang iyong kita','Pindutin ang + Add sa bahagi ng kita.','Ilagay ang paglalarawan, halaga, at hinihinging detalye ng iskedyul.','Pindutin ang Save Allocation para itala ito, o Cancel para isara nang hindi nagse-save.']},
  {en:['Record your expenses','Use + Add in the expense section.','Enter the expense details, amount, category, and schedule shown in the form.','Select Save Expense, then review the entry in the list. Check the amount before saving.'],tl:['Itala ang iyong gastusin','Pindutin ang + Add sa bahagi ng gastusin.','Ilagay ang detalye, halaga, kategorya, at iskedyul na hinihingi sa form.','Pindutin ang Save Expense at suriin ang naitalang entry. Tiyakin ang halaga bago mag-save.']},
  {en:['Review totals and time periods','Use All, Monthly, or the available interval filters to inspect your records.','Check which month and filter are active before interpreting totals and category breakdowns.','The Grocery budget is a separate shopping target; entering it does not create a Budget expense.'],tl:['Suriin ang kabuuan at panahon','Gamitin ang All, Monthly, o ibang filter ng panahon para suriin ang mga tala.','Tingnan ang aktibong buwan at filter bago basahin ang kabuuan at mga kategorya.','Hiwalay na target ang Grocery budget; hindi ito awtomatikong nagdaragdag ng gastusin sa Budget.']}
 ],
 meal: [
  {en:['Meal Planner: choose budget and pax','Set your weekly budget, number of people, and preferred diet.','Pax means the number of people eating. Quick buttons offer 1, 2, 4, 6, or 8 people.','Select Generate Meal Plan to create a weekly schedule.'],tl:['Meal Planner: piliin ang badyet at pax','Ilagay ang lingguhang badyet, bilang ng tao, at nais na uri ng pagkain.','Ang pax ay bilang ng kakain. May mabilis na pagpipilian para sa 1, 2, 4, 6, o 8 tao.','Pindutin ang Generate Meal Plan para gumawa ng iskedyul sa isang linggo.']},
  {en:['Choose dishes yourself','Select Customize Meal Plan to build your own schedule.','Choose meals for breakfast, lunch, and dinner. Use Change to replace a chosen dish.','Complete Meal Plan opens the summary. Clear Week removes the current selections, so use it only when you want to start over.'],tl:['Ikaw ang pumili ng mga putahe','Pindutin ang Customize Meal Plan para gumawa ng sariling iskedyul.','Pumili para sa almusal, tanghalian, at hapunan. Gamitin ang Change para palitan ang putahe.','Binubuksan ng Complete Meal Plan ang buod. Inaalis ng Clear Week ang kasalukuyang mga pinili; gamitin lamang kung magsisimula muli.']},
  {en:['Inspect ingredients and serving sizes','Open a meal name to see the recipe details.','Changing people updates the whole plan. Ingredient amounts scale with pax; cooking times may need adjustment.','Review the measured quantities and cooking instructions before preparing the meal.'],tl:['Suriin ang sangkap at dami ng kakain','Buksan ang pangalan ng putahe para sa detalye ng recipe.','Binabago ng bilang ng tao ang buong plano. Umaayon ang sangkap sa pax; maaaring kailangan ding baguhin ang oras ng pagluluto.','Suriin ang sukat ng mga sangkap at mga hakbang bago magluto.']},
  {en:['Understand meal costs','The breakdown distinguishes priced ingredients from missing prices.','A planning estimate may use a saved recipe allowance. It is not a confirmed shopping total.','Whole packages may cost more than the portion used in a recipe. Rice and extras are included only when listed.'],tl:['Unawain ang gastos sa pagkain','Hiwalay sa detalye ang mga sangkap na may presyo at wala pa.','Maaaring gumamit ng nakatalagang allowance ang planning estimate. Hindi ito tiyak na kabuuang gastos sa pamimili.','Maaaring mas mahal ang buong pakete kaysa sa bahaging gagamitin. Kasama lamang ang kanin at dagdag kung nakalista.']},
  {en:['Save the plan and shop','Name your plan and use Save Meal Plan when the summary offers it.','Use Saved Meal Plans and Refresh to find saved plans.','Add to Grocery List transfers ingredients at the selected pax. It asks before replacing items from a previous meal plan; review quantities and missing prices in Grocery.'],tl:['I-save ang plano at mamili','Pangalanan ang plano at gamitin ang Save Meal Plan kapag lumitaw ito sa buod.','Gamitin ang Saved Meal Plans at Refresh para hanapin ang naka-save na plano.','Inililipat ng Add to Grocery List ang mga sangkap ayon sa pax. Humihingi ito ng pahintulot bago palitan ang mula sa dating plano; suriin ang dami at kulang na presyo sa Grocery.']}
 ],
 prices: [
  {en:['Prices: check the report','Read the update label and status above the watchlist.','DA market prices and DTI SRPs can come from different report dates.','If the live feed is unavailable, review the offline status rather than assuming the figures are current.'],tl:['Prices: tingnan ang ulat','Basahin ang petsa at status sa itaas ng watchlist.','Maaaring magkaiba ang petsa ng DA market prices at DTI SRP.','Kung hindi makuha ang live feed, tingnan ang offline status; huwag ipagpalagay na bago ang mga presyo.']},
  {en:['Browse categories and pages','Choose a category to narrow the price table.','Use the page controls below the table to see more items.','For a searchable list with Add to grocery buttons, open the Grocery tab.'],tl:['Pumili ng kategorya at pahina','Pumili ng kategorya para paliitin ang listahan.','Gamitin ang mga kontrol sa ilalim ng talahanayan para makita ang ibang pahina.','Para sa paghahanap at mga button na Add to grocery, buksan ang Grocery.']},
  {en:['Compare the correct unit','Read the product name, price, selling unit, and notes together.','A kg, a piece, and a specific pack size are not interchangeable. Check brands and product variants too.','The notes identify source, region, and restrictions where available.'],tl:['Ihambing ang tamang yunit','Basahin nang magkasama ang produkto, presyo, yunit, at notes.','Magkaiba ang kilo, piraso, at laki ng pakete. Suriin din ang tatak at uri ng produkto.','Nasa notes ang pinagmulan, rehiyon, at mga kundisyon kung mayroon.']},
  {en:['Handle unavailable prices','An unavailable price is not zero or free.','Supplemental references are labeled separately from DA and DTI data.','Confirm actual shop prices. You can enter a local estimate for an unpriced item in Grocery.'],tl:['Kapag walang presyo','Ang walang presyo ay hindi nangangahulugang libre.','Hiwalay ang label ng supplemental references sa DA at DTI.','Alamin ang aktuwal na presyo sa tindahan. Maaari kang maglagay ng lokal na tantiya para sa walang presyong item sa Grocery.']}
 ],
 grocery: [
  {en:['Grocery: browse and add prices','Use the price list inside Grocery List Tracker.','Search by product or choose a category, then select Add to grocery.','Each click adds one selling unit. Check the unit, source date, and notes before changing the quantity.'],tl:['Grocery: maghanap at magdagdag','Gamitin ang listahan ng presyo sa Grocery List Tracker.','Hanapin ang produkto o pumili ng kategorya, saka pindutin ang Add to grocery.','Isang yunit ang nadaragdag sa bawat pindot. Tingnan ang yunit, petsa, at notes bago baguhin ang dami.']},
  {en:['Add your own item','Use the manual form under Your shopping items.','Enter the name, price per unit, quantity, unit, and category, then select Add Item.','For example, ₱60 per kg with quantity 0.5 and unit kg gives a ₱30 item cost.'],tl:['Magdagdag ng sariling item','Gamitin ang form sa ilalim ng Your shopping items.','Ilagay ang pangalan, presyo kada yunit, dami, yunit, at kategorya, saka pindutin ang Add Item.','Halimbawa: ₱60 kada kg, dami na 0.5, at yunit na kg ay nagkakahalaga ng ₱30.']},
  {en:['Adjust quantities and meal ingredients','Use the quantity field or plus/minus controls on an item.','Whole packs and pieces must use whole quantities. Meal-plan ingredients may be combined before rounding packs up.','Adding a meal plan can replace earlier meal-plan items after confirmation. Check any local prices again after replacement.'],tl:['Baguhin ang dami at sangkap','Gamitin ang kahon ng dami o plus/minus sa item.','Buong bilang ang gamitin para sa pakete at piraso. Maaaring pagsamahin muna ang mga sangkap bago bilugan pataas ang pakete.','Maaaring palitan ng bagong meal plan ang dating mga sangkap matapos kumpirmahin. Suriin muli ang lokal na presyo pagkatapos nito.']},
  {en:['Fill in missing local prices','Look for Price needed and Your local price estimate.','Enter the shop price and the quantity it covers: ₱20 for 10 g means ₱4 for 2 g. Select Save local price.','You can edit the estimate or use Remove local price. These values apply to this list and do not change official price references.'],tl:['Ilagay ang kulang na lokal na presyo','Hanapin ang Price needed at Your local price estimate.','Ilagay ang presyo sa tindahan at daming sakop nito: ₱20 para sa 10 g ay ₱4 para sa 2 g. Pindutin ang Save local price.','Maaaring baguhin o alisin gamit ang Remove local price. Para lamang ito sa listahang ito at hindi binabago ang opisyal na sanggunian.']},
  {en:['Set and review your grocery budget','Enter Grocery budget in Shopping List Summary, then leave the field to save.','The comparison includes every item, even those already bought. It shows estimated money left or overspending.','Partial totals exclude missing prices, so being under the target does not confirm the list fits. This target is saved in this browser; clear the field to remove it.'],tl:['Itakda at suriin ang badyet','Ilagay ang Grocery budget sa Shopping List Summary, saka lumipat sa ibang field para ma-save.','Kasama sa paghahambing ang lahat, pati ang nabili na. Makikita ang tantiyang natitira o labis sa badyet.','Hindi kasama sa partial total ang walang presyo, kaya hindi pa tiyak kung kasya. Sa browser ito naka-save; burahin ang laman para alisin.']},
  {en:['Track your shopping and clean up','Tick an item when bought. The summary separates bought and remaining items.','Delete removes one item. Clear Bought Items removes checked items; Clear All Items empties the list after confirmation.','Changing the tracking routine does not create a separate shopping list. Check your current items before clearing anything.'],tl:['Subaybayan ang pamimili','Lagyan ng tsek ang nabili na. Hiwalay sa buod ang nabili at bibilhin pa.','Isang item ang inaalis ng Delete. Inaalis ng Clear Bought Items ang may tsek; nililinis ng Clear All Items ang lahat matapos kumpirmahin.','Hindi gumagawa ng hiwalay na listahan ang pagbabago ng tracking routine. Suriin ang kasalukuyang laman bago magbura.']}
 ],
 suggestions: [
  {en:['Palengke AI: ask a clear question','Type your question or choose a quick prompt.','Include your budget, number of people, and ingredients you already have.','Ask in English or Filipino; the response follows your question’s language.'],tl:['Palengke AI: malinaw na tanong','I-type ang tanong o pumili ng quick prompt.','Isama ang badyet, bilang ng kakain, at mga sangkap na mayroon ka.','Magtanong sa English o Filipino; susunod ang wika ng sagot sa tanong mo.']},
  {en:['Send and follow up','Select Send or press Enter. Shift+Enter adds a new line.','Wait for the current answer before sending another question.','Ask a follow-up to clarify a suggestion. If a request fails, read the message and try again later.'],tl:['Ipadala at magtanong pa','Pindutin ang Send o Enter. Gumamit ng Shift+Enter para sa bagong linya.','Hintayin ang kasalukuyang sagot bago magpadala ng panibagong tanong.','Magtanong pa para linawin ang mungkahi. Kung pumalya, basahin ang mensahe at subukan muli mamaya.']},
  {en:['Check suggestions before using them','Treat meal costs as estimates unless every listed ingredient is priced.','Review serving sizes, source dates, and ingredients with missing prices.','AI suggestions do not automatically add meals or items to your lists. Use Meal Planner and Grocery to make those changes.'],tl:['Suriin ang mungkahi bago gamitin','Ituring na tantiya ang gastos hangga’t hindi lahat ng sangkap ay may presyo.','Suriin ang dami ng kakain, petsa ng sanggunian, at mga sangkap na walang presyo.','Hindi awtomatikong nagdaragdag sa listahan ang AI. Gamitin ang Meal Planner at Grocery para gawin iyon.']},
  {en:['Start a fresh conversation','Select Clear chat when you want to start over.','This clears the displayed conversation and starts a new chat context.','It does not clear your grocery list or meal plan. You can reopen this guide anytime.'],tl:['Magsimula ng bagong usapan','Pindutin ang Clear chat kung nais magsimula muli.','Nililinis nito ang nakikitang usapan at nagsisimula ng bagong konteksto.','Hindi nito binubura ang grocery list o meal plan. Maaari mong buksan muli ang gabay anumang oras.']}
 ]
};
